### Site info:
title: Geekepub
tagline: 一个出版人的博客
author: geekepub
email: geekepub@163.com
description: "分享" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme"
locale: en_US
timezone: "Asia/Shanghai"

### Personal info and site tools info:
douban_username: 36502585
github_username: geekepub
disqus_shortname: geekepub
favicon: http://7xnix3.com1.z0.glb.clouddn.com/icon.jpg
aboutme: Hi, this is geekepub.  # these are shown on aboutme-sidebar.
aboutme_photo: http://7xnix3.com1.z0.glb.clouddn.com/aboutme.jpg
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "博客推荐"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "分类:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: 阮一峰
        href: http://www.ruanyifeng.com/blog/
        title: 阮一峰的网络日志
      - name: 阳志平
        href: http://www.yangzhiping.com
        title: 阳志平的网志
      - name: 刘未鹏
        href: http://mindhacks.cn
        title: 刘未鹏 | MIND HACKS
      - name: 卢昌海
        href: http://www.changhai.org
        title: 卢昌海个人主页

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
excerpt_separator: <!-- more -->
